//Generated by the daenerys tool.  DO NOT EDIT!
package model

import (
	"gorm.io/datatypes"
	"time"
)

// Catalog [...]
type Catalog struct {
	ID          int            `gorm:"primaryKey;column:id" json:"-"`
	Name        string         `gorm:"column:name" json:"name"`                // 名称
	ParentID    int            `gorm:"column:parent_id" json:"parentId"`       // 上级id
	ChildrenIDs datatypes.JSON `gorm:"column:children_ids" json:"childrenIds"` // 子级ids
	LinkIDs     datatypes.JSON `gorm:"column:link_ids" json:"linkIds"`         // 链接ids
}

// TableName get sql table name.获取数据库表名
func (m *Catalog) TableName() string {
	return "catalog"
}

// Link [...]
type Link struct {
	ID        int       `gorm:"primaryKey;column:id" json:"-"`
	CreatedAt time.Time `gorm:"column:created_at" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updatedAt"`
	Name      string    `gorm:"column:name" json:"name"`
	URL       string    `gorm:"column:url" json:"url"`
	Icon      string    `gorm:"column:icon" json:"icon"`
}

// TableName get sql table name.获取数据库表名
func (m *Link) TableName() string {
	return "link"
}
